### ISSUE TITLE
Backwards compatibility with R like R's backward compatibility with S

### ISSUE THREAD

**Issue by JosiahParry** [dgkf/R#4]
It would be quite cool and interesting if this could be backwards compatible with R, say v 4.0+ so that existing R code can work with it out of the box. Much like how R focused on backwards compatibility with S

**Comment by dgkf** [comment]
Absolutely! This is exactly my thoughts as well. 

I think it's fair to say this is a key design goal that I have for the project.

I don't particularly want to commit the project to being a strict re-implementation of R, but I'd love if it eventually could load R packages to leverage the R package ecosystem - perhaps internally mapping the source code to equivalent `dgkf/R` (for lack of a better name) code.

The project, even in it's infancy today, already introduces some keyword analogs (`fn` in place of `function`, `true`/`false` to save my pinky fingers :stuck_out_tongue_closed_eyes:) as well as `[1, 2, 3]` as a vector creation syntax and `(1, 2, 3)` as a list creation syntax. These are all fully up for debate, but they underscore that the project started as an R-inspired language instead of being strictly an R re-implementation.
